---
- hosts: ansi-test
  tasks:
  - name: Create a directory in /opt/tomcat8
    file:
        path: /opt/tomcat8
        state: directory
        mode: 0755
        owner: tomcat
        group: tomcat

  - name: Download Tomcat from Get_url
    get_url:
        url: https://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
        dest: /opt/tomcat8
        mode: 0755
        group: tomcat
        owner: tomcat 
