---
- hosts: ansi-test
  

  tasks:
    - name: install httpd
      yum:
        name: httpd

    - name: install php
      yum: name={{item}} state=installed
      with_items:  
      - php
      - php-mysql
      - php-pdo
      - php-gd
      - php-mbstring
      
    - name: copy file
      shell: echo "<?php phpinfo (); ?>" > /var/www/html/info.php

    - name: install mariadb
      yum: name={{item}} state=installed
      with_items:
      - mariadb-server
      - mariadb
    
    - name: restart httpd
      service:
        name: httpd
        state: restarted
